export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';

export const FETCH_PRODUCT_SUCCESS = 'FETCH_PRODUCT_SUCCESS';

export const GET_PRODUCT_DETAILS = 'GET_PRODUCT_DETAILS';

export const REGISTER_SUCCES = 'REGISTER_SUCCES';

export const GET_CATEGORY = 'GET_CATEGORY';

export const ADD_TO_CART = 'ADD_TO_CART';

export const GET_CART = 'GET_CART';

export const DELETE_FROM_CART = 'DELETE_FROM_CART';

export const CHECK_WISHLIST_PRODUCT = 'CHECK_WISHILIST_PRODUCT';

export const UPDATE_CART = 'UPDATE_CART';

export const SEARCH_RESULT_LIST = 'SEARCH_RESULT_LIST   '
export const GET_WISHLIST   = 'GET_WISHLIST';